<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite9b9c515e300d5176a920e70281be311
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'JamesHeinrich\\GetID3\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'JamesHeinrich\\GetID3\\' => 
        array (
            0 => __DIR__ . '/..' . '/james-heinrich/getid3/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite9b9c515e300d5176a920e70281be311::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite9b9c515e300d5176a920e70281be311::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite9b9c515e300d5176a920e70281be311::$classMap;

        }, null, ClassLoader::class);
    }
}
